import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="bg-black text-white antialiased">
  {/* Background Glow */}
  <div
    className="
    fixed
    top-[-200px]
    right-[-100px]
    h-[500px]
    w-[500px]
    rounded-full
    bg-blue-500/20
    blur-[120px]
    pointer-events-none
  "
  />

  <div
    className="
    fixed
    bottom-[-200px]
    left-[-100px]
    h-[500px]
    w-[500px]
    rounded-full
    bg-purple-500/20
    blur-[120px]
    pointer-events-none
  "
  />
<Toaster
  position="top-right"
  richColors
/>
  {children}
</body>
    </html>
  );
}
